[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ignored_error_codes = [2018, 9302, 5574]

[profile.default.fuzz]
include_storage = false

[fmt]
line_length = 120
tab_width = 4
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
override_spacing = true
wrap_comments = false
