sequenceDiagram
    title Starport Origination Sequence Diagram


    Box green Orignation
        participant Fulfiller
        participant Starport
        participant CaveatEnforcer
    end

    Box blue Assets
        participant Lender
        participant Borrower
        participant Custodian
        participant FeeRecipient
        participant AdditionalTransferRecipient
    end

    Fulfiller->>Starport: originate

    opt Fulfiller is not Borrower
        loop 1->n
            Starport->>CaveatEnforcer: validate
        end
    end
    opt Fulfiller is not Lender
        loop 1->n
            Starport->>CaveatEnforcer: validate
        end
    end
    loop Transfer 1->n collateral items
        Borrower->>Custodian: transfer collateral
    end
    opt Custodian is not default
        Starport->>Custodian: custody (optional)
    end

    alt Fees Disabled
        loop Transfer 1->n debt items
            Lender->>Borrower: transfer debt
        end
    else Fees Enabled
        opt FeeItems length > 0
            loop Transfer 1->n fee items
                Lender->>FeeRecipient: Move Fee to FeeRecipient
            end
        end
        loop Transfer 1->n debt items
            Lender->>Borrower: Move debt to Borrower - Fee
        end
    end

    opt AdditionalTransferItems length > 0
        loop 1->n
            alt From is Borrower
                Borrower->>AdditionalTransferRecipient: AdditionalTransferItem from Borrower => AdditionalTransferRecipient
            else From is Lender
                Lender->>AdditionalTransferRecipient: AdditionalTransferItem from Lender => AdditionalTransferRecipient
            else From is F
                Fulfiller->>AdditionalTransferRecipient: AdditionalTransferItem from Fulfiller => AdditionalTransferRecipient
            end
        end
    end

    opt Lender is contract
        Starport->>Lender: onLoanOpened
    end