sequenceDiagram
    title Starport Refinance Sequence Diagram



    Box blue
    participant AdditionalTransferRecipient
    participant F as Fulfiller
    end
    Box green
    participant Starport
    participant Pricing
    participant Settlement
    participant CaveatEnforcer
    end

    Box rgb(112,100,0)
    participant B as Borrower
    participant R as New Lender
    participant L as Original Lender
    participant Originator as Original Originator
    end

    F->>Starport: refinance
    Starport->>Pricing: getRefinanceConsideration
    Pricing->>Starport: (SpentItem[] ConsiderPayment, SpentItem[] CarryPayment, AdditionalTransfer[] AT)

    Starport->>Starport: _settleLoan
    Starport->>Settlement: postRepayment

    loop Transfer 1->n ConsiderPayment items
        R->>L: Move ConsiderPayment to Lender
    end
    opt CarryPayment length > 0
        R->>Originator: Move CarryPayment to Originator
    end

    opt F is not Refinancer and F is not approved
        loop Validate 1->n Caveats
            Starport->>CaveatEnforcer: validate
        end
    end
    opt AdditionalTransferItems length > 0
        Starport->>Starport: validateAdditionalTransfers
        loop 1->n
            alt From is Borrower
                B->>AdditionalTransferRecipient: AdditionalTransferItem from Borrower -> AdditionalTransferRecipient
            else From is Lender
                R->>AdditionalTransferRecipient: AdditionalTransferItem from Refinancer -> AdditionalTransferRecipient
            else From is F
                F->>AdditionalTransferRecipient: AdditionalTransferItem from Fulfiller -> AdditionalTransferRecipient
            end
        end
    end
    Starport->>Starport: _issueLoan