name: Lint, Test

on: push

env:
  FOUNDRY_PROFILE: ci

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn

      - uses: foundry-rs/foundry-toolchain@v1

      - name: Lint
        run: forge fmt --check

      - name: Snapshot
        run: forge snapshot --check --no-match-path '*fuzz*' --no-match-test 'testEIP712Signing'

      - name: Test
        run: forge test -vvv --no-match-test 'testEIP712Signing'
